name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes (approx)
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping App URL
        run: |
          # Use a real User-Agent and follow redirects
          curl -L -v -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (HTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://india-gis.streamlit.app/

